### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by anbraten** [geprog/former#4]
- [x] make a vue component library exporting form-builder and form-options-panel
- [x] add a playground and deploy it to github pages
- [ ] add basic input components
  - [x] text input
  - [ ] selection list / dropdown
  - [ ] button
  - [x] checkbox
  - [ ] radio button
  - [ ] file
  - [x] text area
  - [x] number input
- [ ] input options specific for the different input types
  - [ ] conditions (only show if x is true)
  - [ ] validation rules
- [ ] layout components
  - [ ] group (nesting components and data)
  - [ ] list
